CPSB_RECRUITMENT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('mozilla_django_oidc.urls')),
    path('accounts/', include('allauth.urls')),
    path('recruitment/', include('recruitment.urls')),
]

users/urls.py
from django.urls import path, include
from .views import (
	home, profile, CompleteProfile, 
	GroupCreateView, GroupListView, 
	AddGroupUser, RemoveGroupUser
)
urlpatterns = [
    path('', home, name='home'),
    path('users/profile/', profile, name='profile'),
    path('users/complete-profile/', CompleteProfile.as_view(), name='complete-profile'),
    path('users/groups/add/', GroupCreateView.as_view(), name='add-group'),
    path('users/groups/lists/', GroupListView.as_view(), name='group-list'),
    path('users/groups/<int:pk>/members/add/', AddGroupUser.as_view(), name='add-group-member'),
    path('users/groups/<int:pk>/members/remove/', RemoveGroupUser.as_view(), name='remove-group-member')
]

recruitment/models.py
import datetime
import pytz

from django.db import models
from django.conf import settings

from month.models import MonthField
from django_fsm import FSMField, transition

from users.models import GENDER

utc=pytz.UTC

ACADEMIC_LEVELS = (
	(0, 'Artisan Certificate'),
	(1, 'Certifificate'),
	(2, 'Diploma'),
	(3, 'Higher Diploma'),
	(4, 'Bachelors Degree'),
	(5, 'Masters Degree'),
	(6, 'PhD.'),
	)

GRADES = (
		(1, 'A'),
		(2, 'A-'),
		(3, 'B+'),
		(4, 'B'),
		(5, 'B-'),
		(6, 'C+'),
		(7, 'C'),
		(8, 'C-'),
		(9, 'D+'),
		(10, 'D'),
		(11, 'D-'),
		(12, 'E'),
	)

ETHNIC_GROUPS = (
		('kikuyu', 'Kikuyu'),
		('meru', 'Meru'),
		('kisii', 'Kisii'),
		('embu', 'Embu'),
		('luhya', 'Luhya'),
		('swahili', 'Swahili'),
		('mijikenda', 'Mijikenda'),
		('luo', 'Luo'),
		('maasai', 'Maasai'),
		('turkana', 'Turkana'),
		('samburu', 'Samburu'),
		('kalenjin', 'Kalenjin'),
		('somali', 'Somali'),
		('el-molo', 'El Molo'),
		('boran', 'Boran'),
		('burji-dassenich', 'Burji Dassenich'),
		('gabbra', 'Gabbra'),
		('orma', 'Orma'),
		('sakuya', 'Sakuya'),
		('boni', 'Boni'),
		('wata', 'Wata'),
		('yaaka', 'Yaaka'),
		('daholo', 'Daholo'),
		('rendille', 'Rendille'),
		('galla', 'Galla'),
	)

REVIEW_CHOICES = (
    (True, u'Approve'),
    (False, u'Disapprove'),  
)

ACTION_CHOICES = (
    ('shortlist', 'Shortlisting'),
    ('appoint', 'Appointing'),  
)

# Create your models here.
class Qualification(models.Model):
	'''
	- level
	- course
	- institution
	- period

	'''
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='qualifications', on_delete=models.CASCADE)
	level = models.PositiveSmallIntegerField(choices=ACADEMIC_LEVELS)
	course = models.CharField(max_length=200)
	institution = models.CharField(max_length=200)
	period_from = MonthField("Commencement Period", null=True, blank=True)
	period_to = MonthField("Conclusion Period",blank=True, null=True)

	def __str__(self):
		return f'{self.get_level_display()} - {self.course}'

class Employment(models.Model):
	'''
	- organization
	- designation
	- period

	'''
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='employment_records', on_delete=models.CASCADE)
	designation = models.CharField(max_length=200, null=True, blank=True)
	organization = models.CharField(max_length=200, null=True, blank=True)
	period_from = MonthField("Starting Period", blank=True, null=True)
	period_to = MonthField("End Period",blank=True, null=True)
	current = models.BooleanField('I currently work here', default=False)

	def __str__(self):
		return f'{self.designation}'

class Department(models.Model):
	name = models.CharField(max_length=120)

	def __str__(self):
		return self.name

	def active_vacancies_count(self):
		vacancies = [vacancy for vacancy in self.vacancies.all() if vacancy.is_active]
		return len(vacancies)

class Vacancy(models.Model):
	'''
	- department
	- name
	- experience
	- requirements
	- timelines

	'''
	department = models.ForeignKey(Department, related_name='vacancies', on_delete=models.CASCADE)
	vacancy_number = models.CharField(max_length=20,  null=True)
	name = models.CharField(max_length=200)
	experience = models.PositiveSmallIntegerField()
	minimum_kcse_grade = models.IntegerField("Minimum K.C.S.E Grade", choices=GRADES, null=True)
	requirements = models.TextField()
	requires_compliances = models.BooleanField(default=True)
	opening_date = models.DateTimeField(auto_now_add=True)
	closing_date = models.DateTimeField()
	status = FSMField(default='active')
	meta_status = FSMField(default='awaiting_action')

	class Meta:
		verbose_name_plural='Vacancies'
		permissions = (
            ("can_view_active_vacancies", "Can view active vacancies"),
            ("can_view_closed_vacancies", "Can view closed vacancies"),
            ("can_add_vacancies", "Can add vacancies"),
            ("can_edit_vacancies", "Can edit vacancies"),
            ("can_delete_vacancies", "Can delete vacancies")
        )

	def __str__(self):
		return self.name

	@transition(field=status, source='active', target='closed')
	def close(self):
		"""
		This function may contain side-effects,
		like updating caches, notifying users, etc.
		The return value will be discarded.
		"""

	@transition(field=status, source='closed', target='shortlisting_done')
	def set_shortlisted(self):
		"""
		This function may contain side-effects,
		like updating caches, notifying users, etc.
		The return value will be discarded.
		"""

	@transition(field=status, source='shortlisting_done', target='appointing_done')
	def set_appointed(self):
		"""
		This function may contain side-effects,
		like updating caches, notifying users, etc.
		The return value will be discarded.
		"""
	@transition(field=meta_status, source='awaiting_action', target='staged')
	def stage(self):
		"""
		This function may contain side-effects,
		like updating caches, notifying users, etc.
		The return value will be discarded.
		"""
	@transition(field=meta_status, source='*', target='awaiting_full_consent')
	def set_uncertain(self):
		"""
		This function may contain side-effects,
		like updating caches, notifying users, etc.
		The return value will be discarded.
		"""
	@transition(field=meta_status, source=['staged', 'awaiting_full_consent', 'awaiting_approval'], target='awaiting_approval')
	def set_awaiting_approval(self):
		"""
		This function may contain side-effects,
		like updating caches, notifying users, etc.
		The return value will be discarded.
		"""
	@transition(field=meta_status, source='awaiting_approval', target='finalized')
	def finalize(self):
		"""
		This function may contain side-effects,
		like updating caches, notifying users, etc.
		The return value will be discarded.
		"""
	@property
	def next_action(self):
		action = 'shortlist' if self.is_closed else 'appoint'
		return action

	@property
	def is_active(self):
		if self.status == 'active':
			return True
		return False

	@property
	def is_closed(self):
		if self.status == 'closed':
			return True
		return False

	@property
	def has_been_shortlisted(self):
		if self.status == 'shortlisting_done':
			return True
		return False

	@property
	def has_been_appointed(self):
		if self.status == 'appointing_done':
			return True
		return False

	@property
	def allows_staging(self):
		if self.applications.count():
			if self.status in ['closed', 'shortlisting_done'] and self.meta_status in ['awaiting_action', 'finalized']:
				return True
		return False

	@property
	def in_process(self):
		if self.applications.count():
			if self.meta_status not in ['awaiting_action', 'finalized']:
				return True
		return False

	@property
	def shortlisting_reviews_count(self):
		_shortlisting_reviews_count = self.reviews.filter(action='shortlist').count()
		return _shortlisting_reviews_count

	@property
	def appointment_reviews_count(self):
		_appointment_reviews_count = self.reviews.filter(action='appoint').count()
		return _appointment_reviews_count

	@property
	def shortlisting_approvals_count(self):
		_shortlisting_approvals_count = self.reviews.filter(approval=True, action='shortlist').count()
		return _shortlisting_approvals_count

	@property
	def shortlisting_disapprovals_count(self):
		_shortlisting_disapprovals_count = self.reviews.filter(approval=False, action='shortlist').count()
		return _shortlisting_disapprovals_count

	@property
	def appointment_approvals_count(self):
		_appointment_approvals_count = self.reviews.filter(approval=True, action='appoint').count()
		return _appointment_approvals_count

	@property
	def appointment_disapprovals_count(self):
		_appointment_disapprovals_count = self.reviews.filter(approval=False, action='appoint').count()
		return _appointment_disapprovals_count

class Review(models.Model):
	vacancy = models.ForeignKey(Vacancy, related_name='reviews', on_delete=models.CASCADE)
	user = models.ForeignKey('users.User', related_name='vacancy_reviews', on_delete=models.CASCADE)
	approval = models.BooleanField(choices=REVIEW_CHOICES, null=True)
	action = models.CharField(max_length=10, choices=ACTION_CHOICES, default='shortlist')
	is_final = models.BooleanField(default=False)	

class County(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return f'{self.name}'

class Subcounty(models.Model):
	county = models.ForeignKey(County, related_name='subcounties', on_delete=models.CASCADE)
	name = models.CharField(max_length=200)

	def __str__(self):
		return f'{self.name}'

class Ward(models.Model):
	county = models.ForeignKey(County, related_name='wards', on_delete=models.CASCADE, null=True)
	subcounty = models.ForeignKey(Subcounty, related_name='wards', on_delete=models.CASCADE)
	name = models.CharField(max_length=200)

	def __str__(self):
		return f'{self.name}'

class Sublocation(models.Model):
	county = models.ForeignKey(County, related_name='sublocations', on_delete=models.CASCADE, null=True)
	subcounty = models.ForeignKey(Subcounty, related_name='sublocations', on_delete=models.CASCADE)
	ward = models.ForeignKey(Ward, related_name='sublocations', on_delete=models.CASCADE)
	name = models.CharField(max_length=200)

	def __str__(self):
		return f'{self.name}'

class ProfessionalBody(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='professional_bodies', on_delete=models.CASCADE)
	name = models.CharField(max_length=150)
	registration_number = models.CharField(max_length=150)

class Referee(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='referees', null=True)
	full_name = models.CharField(max_length=300)
	occupation = models.CharField(max_length=200)
	mobile_number = models.CharField(max_length=13)
	email = models.EmailField(unique=True)
	period_known = models.CharField(max_length=100)

class Application(models.Model):
	'''
	INTERNAL FIELDS
	- personal details
		- Profile Info
		- Ethnicity
		- Disability Status		
	- other personal details
		- Criminal Conviction
		- Dismissal
	- abilities
	- compliance details

	EXTERNAL RELATIONS

templates/recruitment/lists/vacancies/_admin_dropdown.html
<div class="dropdown-menu">
  <a href="{% url 'vacancy-details' vacancy.id %}" class="dropdown-item btn-sm">
    <i class="fas fa-long-arrow-alt-right"></i> View Details
  </a>
	<a href="{% url 'applicants-list' vacancy.id %}" class="update-vacancy dropdown-item btn-sm">
  	<i class="fas fa-eye"></i> View Applicants
  </a>
  <button type="button" class="update-vacancy dropdown-item btn-sm" data-id="{% url 'update-vacancy' vacancy.id %}"> 
    <i class="far fa-edit"></i> Update Vacancy
  </button>
  <div class="dropdown-divider"></div>
  <button type="button" class="delete-vacancy dropdown-item btn-sm text-danger" data-id="{% url 'delete-vacancy' vacancy.id %}"> 
    <i class="fas fa-trash"></i> Delete Vacancy
  </button>
</div>

templates/recruitment/lists/vacancies/_staff_dropdown.html
<div class="dropdown-menu">
  <a href="{% url 'vacancy-details' vacancy.id %}" class="dropdown-item btn-sm">
    <i class="fas fa-long-arrow-alt-right"></i> View Details
  </a>
  <a href="{% url 'applicants-list' vacancy.id %}" class="update-vacancy dropdown-item btn-sm">
  	<i class="fas fa-eye"></i> &nbsp;
  	View Applicants
  </a>
</div>

templates/recruitment/lists/vacancies/active_vacancies_applicant.html
{% extends "layout/layout.html" %}
{% load static %}
{% block section_header %}
  	<section class="section-header">    
	<h1>Vacancies</h1>
	<div class="section-header-breadcrumb">
		<div class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i> &nbsp; Home</a></div>
		<div class="breadcrumb-item">Vacancies</div>
	</div>
  	</section>
{% endblock section_header %}
{% block content %}
<h2 class="section-title">Active Vacancies</h2>
<div class="card shadow">
	<div class="card-body d-none d-lg-block">
		<div class="table-responsive">
          	<table class="table text-center">
	            <thead>
	              <tr>
	                <th>S/No</th>
	                <th>Vacancy Number</th>
	                <th>Vacancy Name</th>
	                <th>Closing Date</th>
	                <th>Action</th>
	              </tr>
	            </thead>
	            <tbody>
	              {% for vacancy in vacancies %}
	                <tr>
	                	<td>{{forloop.counter}}</td>
	                  	<td>{{vacancy.vacancy_number}}</td> 
	                  	<td>{{vacancy.name}}</td>
	                  	<td>{{vacancy.closing_date}}</td>
	                  	<td>
	                  		[<a class="vacancy-details btn-sm" href="#" data-id="{% url 'vacancy-requirements' vacancy.id %}"> <i class="fas fa-tasks"></i> Requirements </a>]
	                  		[<a class="btn-sm" href="{% url 'vacancy-details' vacancy.id %}"> <i class="fas fa-graph"></i> Progress </a>]
	                  		[<a href="{% url 'apply' vacancy.id %}" class="btn-sm"> <i class="fas fa-sign-out-alt"></i> Apply </a>]
	                  	</td>                 
	                </tr>               
	              {% endfor %}                  
	            </tbody>
          	</table>
        </div>
	</div>
	<div class="card-body d-lg-none">
		<ul class="list-group shadow">
        	{% if vacancies %}
	        	{% for vacancy in vacancies %}
					<li class="list-group-item pb-0">
					  	<h6><span class="font-weight-bold">Vacancy</span>: {{vacancy.name}}</h6>
					  	<p><span class="font-weight-bold">V/Number</span>: {{vacancy.vacancy_number}}</p>
					  	<p><span class="font-weight-bold">Deadline</span>: {{vacancy.closing_date}}</p>
					  	<div class="my-2">					  		
					  		[<a class="vacancy-details text-primary" data-id="{% url 'vacancy-details' vacancy.id %}"> <i class="fas fa-tasks"></i> View Details </a>] [<a href="{% url 'apply' vacancy.id %}"><i class="fas fa-sign-out-alt"></i> Apply</a>]
					  	</div>
					</li>
	        	{% endfor %}
	        	{% else %}
	        	<p class="mx-2">No active vacancies</p>
        		
        	{% endif %}
		</ul>
	</div>
</div>
	
{% endblock content %}

{% block customjs %}
<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $('#vacancies-link').addClass('active');
    $('#active-vacancies-link').addClass('active');

    $('.table').DataTable({
      // "bLengthChange": false,
      // "bFilter": false,
    });
    $(".vacancy-details").each(function () {
        $(this).modalForm({
          formURL: $(this).data('id')
        });
    });
  });
</script>  
{% endblock customjs %}

templates/recruitment/lists/vacancies/active_vacancies_staff.html
{% extends "layout/staff_layout.html" %}
{% load static %}
{% block section_header %}
  	<section class="section-header">    
	<h1>Vacancies</h1>
	<div class="section-header-breadcrumb">
		<div class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i> &nbsp; Home</a></div>
		<div class="breadcrumb-item">Active Vacancies</div>
	</div>
  	</section>
{% endblock section_header %}
{% block content %}
<h2 class="section-title">Active Vacancies</h2>
<div class="card shadow">
	<div class="card-body">
		{% if perms.recruitment.can_add_vacancies %}
		<button class="mb-3 btn btn-primary btn-shadow" id="add-vacancy">
			<i class="fas fa-plus-circle"></i> Add Vacancy
		</button>
		{% endif %}
		<div class="table-responsive">
          	<table class="table text-center">
	            <thead>
	              <tr>
	                <th>S/No</th>
	                <th>Vacancy Number</th>
	                <th>Vacancy Name</th>
	                <th>Closing Date</th>
	                <th>Action</th>
	              </tr>
	            </thead>
	            <tbody>
	              {% for vacancy in vacancies %}
	                <tr>
	                	<td>{{forloop.counter}}</td>
	                  	<td>{{vacancy.vacancy_number}}</td> 
	                  	<td>{{vacancy.name}}</td>
	                  	<td>{{vacancy.closing_date}}</td>
	                  	<td>
	                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle">                
	                          <i class="fas fa-ellipsis-v"></i>
	                        </a>
	                        <div class="dropdown-menu">
	                        	<a href="{% url 'vacancy-details' vacancy.id %}" class="dropdown-item btn-sm">
														  	<i class="fas fa-long-arrow-alt-right"></i> Progress &amp; Details
														</a>
														<a href="{% url 'applicants-list' vacancy.id %}" class="dropdown-item btn-sm">
														  	<i class="fas fa-eye"></i> View Applicants
														</a>
														<div class="dropdown-divider"></div>
														{% if perms.recruitment.can_edit_vacancies and perms.recruitment.can_delete_vacancies %}
														  	<button type="button" class="update-vacancy dropdown-item btn-sm" data-id="{% url 'update-vacancy' vacancy.id %}"> 
														    	<i class="far fa-edit"></i> Update Vacancy
														  	</button>
															<button type="button" class="delete-vacancy dropdown-item btn-sm text-danger" data-id="{% url 'delete-vacancy' vacancy.id %}"> 
															    <i class="fas fa-trash"></i> Delete Vacancy
															</button>									
														{% endif %}
													</div>
	                                                
                      	</td>                 
	                </tr>               
	              {% endfor %}                  
	            </tbody>
          	</table>
        </div>
	</div>
</div>
	
{% endblock content %}

{% block customjs %}
<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $('#vacancies-link').addClass('active');
    $('#active-vacancies-link').addClass('active');
    $('.table').DataTable();
    $("#add-vacancy").modalForm({
        formURL: "{% url 'add-vacancy' %}"
    });
    $(".update-vacancy").each(function () {
        $(this).modalForm({
          formURL: $(this).data('id')
        });
    });
    $(".delete-vacancy").each(function () {
        $(this).modalForm({
          formURL: $(this).data('id')
        });
    });
  });
</script>  
{% endblock customjs %}

templates/recruitment/lists/vacancies/finalized_vacancies.html
{% extends "layout/staff_layout.html" %}
{% load static %}
{% load user_groups %}

{% block section_header %}
  	<section class="section-header">    
	<h1>Vacancies</h1>
	<div class="section-header-breadcrumb">
		<div class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i> &nbsp; Home</a></div>
		<div class="breadcrumb-item">Finalized Vacancies</div>
	</div>
  	</section>
{% endblock section_header %}
{% block content %}
<h2 class="section-title">Finalized Vacancies</h2>
<div class="card shadow">
	<div class="card-body">
		<div class="table-responsive">
          	<table class="table text-center">
	            <thead>
	              <tr>
	                <th>S/No</th>
	                <th>Vacancy Number</th>
	                <th>Vacancy Name</th>
	                <th>Appointed Candidates</th>
	                <th>Action</th>
	              </tr>
	            </thead>
	            <tbody>
	              {% for vacancy in vacancies %}
	                <tr>
	                	<td>{{forloop.counter}}</td>
	                  	<td>{{vacancy.vacancy_number}}</td> 
	                  	<td>{{vacancy.name}}</td>
	                  	<td>{{vacancy.appointed_candidates}}</td>
	                  	<td>
	                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle">                
	                          <i class="fas fa-ellipsis-v"></i>
	                        </a>
                        	<div class="dropdown-menu">
		                        <a href="{% url 'vacancy-details' vacancy.id %}" class="dropdown-item btn-sm">
															<i class="fas fa-long-arrow-alt-right"></i>  &nbsp; View Details
														</a>
		                        {% if user|exists_in_group:"STAFF" %}
															  <a href="{% url 'appointed-candidates-list' vacancy.id %}" class="update-vacancy dropdown-item btn-sm">
															  	<i class="fas fa-eye"></i> &nbsp;
															  	Appointed Candidates
															  </a>
		                        {% endif %}
													</div>
                      	</td>                 
	                </tr>               
	              {% endfor %}                  
	            </tbody>
          	</table>
        </div>
	</div>
</div>
	
{% endblock content %}

{% block customjs %}
<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $('#vacancies-link').addClass('active');
    $('#finalized-vacancies-link').addClass('active');

    $('.table').DataTable();
    $(".update-vacancy, .delete-vacancy").each(function () {
        $(this).modalForm({
          // modalID: "#modal-crud",
          formURL: $(this).data('id')
        });
    });
  });
</script>  
{% endblock customjs %}

templates/recruitment/lists/vacancies/vacancy_details.html
{% extends "layout/staff_layout.html" %}
{% load user_groups %}
{% load static %}
{% block section_header %}
  	<section class="section-header">    
	<h1>{{vacancy}}</h1>
	<div class="section-header-breadcrumb">
		<div class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i> &nbsp; Home</a></div>
		<div class="breadcrumb-item"><a href="{% url 'active-vacancies-list' %}"><i class="fas fa-tasks"></i> &nbsp; Vacancies</a></div>
		<div class="breadcrumb-item">{{vacancy}}</div>
	</div>
  	</section>
{% endblock section_header %}
{% block content %}
<h2 class="section-title">Vacancy Progress</h2>
<div class="row">
	<div class="col-md-7">
		<div class="activities">
			<div class="activity">
				<div class="activity-icon bg-dark text-white shadow-dark">
                  <i class="fas fa-clipboard-list"></i>
                </div>
                <div class="activity-detail">
                  <div class="mb-2">
                    <span class="text-job text-dark">Current Stage</span>
                    <span class="bullet"></span>
                    <a class="text-job" href="#">{{vacancy.status}}</a>                    
                  </div>
                  <p>This is the current status for the vacancy {{vacancy}}.</p>
                </div>
			</div>
			{% if previous_milestones %}
				{% for key, value in previous_milestones reversed %}
		            <div class="activity">
		                <div class="activity-icon bg-primary text-white shadow-primary">
		                  <i class="fas fa-check"></i>
		                </div>
		                <div class="activity-detail">
		                  <div class="mb-2">
		                    <span class="text-job">{{key}}</span>
		                    {% if value.useful_links %}
			                    <div class="float-right dropdown">
			                      <a href="#" data-toggle="dropdown"><i class="fas fa-ellipsis-h"></i></a>
			                      <div class="dropdown-menu">
			                        <div class="dropdown-title">Options</div>
			                        {% for k, v in value.useful_links.items %}
			                        	<a href="{{v.url}}" class="dropdown-item has-icon"><i class="{{v.icon}}"></i> {{k}}</a>		                        	
			                        {% endfor %}		                        
			                      </div>
			                    </div>	                    	
		                    {% endif %}
		                  </div>
		                  <p>{{value.description}}.</p>
		                </div>
		            </div>				
				{% endfor %}
			{% endif %}
        </div>
	</div>
	<div class="col-md-5">
		<div class="activities">
			{% if next_milestone %}				
				<div class="activity">
					<div class="activity-icon bg-secondary text-white shadow-secondary">
	                  <i class="fas fa-spinner fa-pulse"></i>
	                </div>
	                <div class="activity-detail">
	                  <div class="mb-2">
	                    <span class="text-job text-dark">Next Milestone</span>
	                    <span class="bullet"></span>
	                    <a class="text-job" href="#">{{next_milestone}}</a>                    
	                  </div>
	                  <p>The next step for this vacancy is: {{next_milestone}}.</p>
	                </div>
				</div>
			{% endif %}
			{% if user|exists_in_group:"BOARD_MEMBERS" %}
				{% if appointment_reviews %}
					<div class="activity">						
		                <div class="activity-detail">
		                  	<div class="mb-2">
			                    <span class="text-job text-dark">Incase you missed</span>
			                    <span class="bullet"></span>
			                    <a class="text-job" href="#">Appointment Reviews</a>                    
		                  	</div>
			                <div class="table-responsive">
					          	<table class="table table-bordered table-sm" id="approvers-table">
						            <thead>
						              <tr>
						                <th>Name</th>
						                <th>Action</th>			                
						              </tr>
						            </thead>
						            <tbody>
						              {% for review in appointment_reviews %}
						              <tr>
						                  	<td>
						                  		{{review.user.get_full_name}}
						                  		{% if review.user == user %}
						                  			<i class="fas fa-check-circle text-primary"></i>
						                  		{% endif %}
						                  	</td>		                  	
						                  	<td>{{review.get_approval_display}}d</td>                
						                </tr>               
						              {% endfor %}                  
						            </tbody>
					          	</table>
					        </div>
		                </div>
					</div>
				{% endif %}
				{% if shortlisting_reviews %}
					<div class="activity">						
		                <div class="activity-detail">
		                  	<div class="mb-2">
			                    <span class="text-job text-primary">Incase you missed</span>
			                    <span class="bullet"></span>
			                    <a class="text-job" href="#">Shortlisting Reviews</a>                    
		                  	</div>
			                <div class="table-responsive">
					          	<table class="table table-bordered table-sm" id="approvers-table">
						            <thead>
						              <tr>
						                <th>Name</th>
						                <th>Action</th>			                
						              </tr>
						            </thead>
						            <tbody>
						              {% for review in shortlisting_reviews %}
						              <tr>
						                  	<td>
						                  		{{review.user.get_full_name}}
						                  		{% if review.user == user %}
						                  			<i class="fas fa-check-circle text-primary"></i>
						                  		{% endif %}
						                  	</td>		                  	
						                  	<td>{{review.get_approval_display}}d</td>                
						                </tr>               
						              {% endfor %}                  
						            </tbody>
					          	</table>
					        </div>
		                </div>
					</div>
				{% endif %}
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}